# Generated by Django 3.1.2 on 2021-02-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20210205_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
