# Generated by Django 3.1.2 on 2021-02-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20210205_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
