# Generated by Django 3.1.2 on 2021-02-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20210205_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0)),
                ('user_email', models.CharField(max_length=50)),
                ('comment_id', models.IntegerField(default=0)),
                ('comment_content', models.TextField()),
            ],
        ),
    ]
