# Generated by Django 3.1.2 on 2021-02-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_post_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post_Comment',
        ),
        migrations.DeleteModel(
            name='Post_Test',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Collection',
        ),
    ]
