# Generated by Django 3.1.2 on 2021-03-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_auto_20210305_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post_Comment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Collection',
        ),
    ]
