# Generated by Django 3.1.2 on 2021-03-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0013_post_post_comment_user_user_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
