# Generated by Django 3.1.2 on 2021-03-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0014_remove_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_comment',
            name='comment_id',
        ),
    ]
