# Generated by Django 3.1.2 on 2021-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0015_remove_post_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
