# Generated by Django 3.1.2 on 2021-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0017_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_place',
            field=models.IntegerField(default=0),
        ),
    ]
