# Generated by Django 3.1.2 on 2021-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0018_photo_photo_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='User_Collection',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=50),
        ),
    ]
