# Generated by Django 3.1.2 on 2021-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0018_photo_photo_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='User_Collection',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
    ]
