# Generated by Django 3.1.2 on 2021-04-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0019_auto_20210422_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=20),
        ),
    ]
